[package]
name = "bevy_p2p"
version.workspace = true
edition.workspace = true

[dependencies]
async-channel = "2.5.0"
bevy = { workspace = true, features = [
    "async_executor",
    "bevy_log",
] }
distributed-topic-tracker = "0.2.0"
iroh = "0.92.0"
iroh-gossip = "0.92.0"
